language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10

stages:
  - lint
  - test

jobs:
  include:
  - stage: lint
    script: yarn lint
  - stage: test
    script: yarn test
  - 
    if: branch = master AND type != pull_request
    node_js: 8
    script: yarn test
  - 
    if: branch = master AND type != pull_request
    node_js: 9
    script: yarn test

before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: yarn deploy-example --token=$NOW_TOKEN
    skip_cleanup: true
    on:
      condition: $SHOULD_BUILD = true
      all_branches: true
      master: false
  - provider: script
    script: yarn deploy-example --token=$NOW_TOKEN && now alias --token=$NOW_TOKEN
    skip_cleanup: true
    on:
      master: true

# Run push builds only on aster
branches:
  only:
    - master

notifications:
  email: false

